# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './code/ui/launcher.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(360, 419)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMaximumSize(QtCore.QSize(400, 419))
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setMinimumSize(QtCore.QSize(0, 60))
        self.frame.setMaximumSize(QtCore.QSize(16777215, 60))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setMinimumSize(QtCore.QSize(360, 353))
        self.frame_2.setMaximumSize(QtCore.QSize(360, 353))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.leUsername = QtWidgets.QLineEdit(self.frame_2)
        self.leUsername.setObjectName("leUsername")
        self.verticalLayout_2.addWidget(self.leUsername)
        self.lePassword = QtWidgets.QLineEdit(self.frame_2)
        self.lePassword.setObjectName("lePassword")
        self.verticalLayout_2.addWidget(self.lePassword)
        self.leUrl = QtWidgets.QLineEdit(self.frame_2)
        self.leUrl.setObjectName("leUrl")
        self.verticalLayout_2.addWidget(self.leUrl)
        self.pbSignin = QtWidgets.QPushButton(self.frame_2)
        self.pbSignin.setObjectName("pbSignin")
        self.verticalLayout_2.addWidget(self.pbSignin)
        self.lbMessage = QtWidgets.QLabel(self.frame_2)
        self.lbMessage.setText("")
        self.lbMessage.setAlignment(QtCore.Qt.AlignCenter)
        self.lbMessage.setObjectName("lbMessage")
        self.verticalLayout_2.addWidget(self.lbMessage)
        self.pbEnter = QtWidgets.QPushButton(self.frame_2)
        self.pbEnter.setObjectName("pbEnter")
        self.verticalLayout_2.addWidget(self.pbEnter)
        self.verticalLayout.addWidget(self.frame_2)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.leUsername, self.lePassword)
        MainWindow.setTabOrder(self.lePassword, self.leUrl)
        MainWindow.setTabOrder(self.leUrl, self.pbSignin)
        MainWindow.setTabOrder(self.pbSignin, self.pbEnter)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "AssloudTool"))
        self.leUsername.setText(_translate("MainWindow", "admin"))
        self.leUsername.setPlaceholderText(_translate("MainWindow", "手机号/邮箱"))
        self.lePassword.setText(_translate("MainWindow", "admin"))
        self.lePassword.setPlaceholderText(_translate("MainWindow", "密码"))
        self.leUrl.setText(_translate("MainWindow", "yumei209"))
        self.pbSignin.setText(_translate("MainWindow", "登录"))
        self.pbEnter.setText(_translate("MainWindow", "进入"))
